### ISSUE TITLE
audio capture problem under Windows 8.1 with Surface Pro 3

### ISSUE THREAD

**Issue by gandalfliang** [rdp/virtual-audio-capture-grabber-device#13]
Using ffmpeg and audio_sniffer to capture system sound under windows 8.1,here is the command line:
ffmpeg -y -f dshow -i audio="virtual-audio-capturer" output.mp3

the problem is when there's no sound when start recording, and play sound(like a song for example) in the middle of the recording, the output file would probably starts playing the sound from the beginning(00:00:00), which means it "cut off" the "blank" sound before the real sound begins. Help please.

**Comment by FrankOcean11** [comment]
m looking for a windows C#/C++ self contain program that can record any sounds coming from the mic connected to my pc Win 8.1 Surface pro2 

i already have my source made up and am simply looking to embed functions i can use to trigger events that can tell my program to take THAT rec audio and pass it thru THAT virtual-audio-capture-grabber-device and store THAT virtual-audio-capture-grabber-device output file from THAT folder with time and date so tha i can have my program later on parse thru it by using those keys/tags "time & date" (metadata) 

is this program for me ? im looking for something very basic small and self contain or something i can embed on to my code itself.

**Comment by rdp** [comment]
You could do a directshow graph I suppose...or just run ffmpeg :)

**Comment by rdp** [comment]
hopefully fixed now
