### ISSUE TITLE
FFMpeg can not find virtual audio capture after  I register the dll to windows 7.

### ISSUE THREAD

**Issue by dttlgotv** [rdp/virtual-audio-capture-grabber-device#14]
I can register the dll successfully into system. But I use "ffmpeg -list_devices true -f dshow -i dummy" to list the devices, the virtual audio capture can not be found.

**Comment by rdp** [comment]
is your "32 bit'edness" lined up (vs. 64 bit)?

**Comment by dttlgotv** [comment]
Now it is well. I used wrong dll.
