### ISSUE TITLE
the recorded audio can not right.

### ISSUE THREAD

**Issue by dttlgotv** [rdp/virtual-audio-capture-grabber-device#15]
I used ffmpeg command line to record the speaker audio well.
   command:
　　　　>ffmpeg -f dshow -i audio="virtual-audio-capturer" gxh.wav

 But after I write ffmpeg codes to record the speaker sound, it listen very badly. 　avformat_open_input and av_read_frame can be called well.

So can you give me some hint? What is the endian used in it?

**Comment by rdp** [comment]
What is your registry values in
HKEY_CURRENT_USER\\
SOFTWARE\\virtual_audio_capture"

**Comment by dttlgotv** [comment]
I just call "regsvr32  %~dp0\audio_sniffer.dll".  And ffmpeg command can run well, the recorded speaker sound is well. But I write some ffmpeg codes to use it, the sound is bad.

the values is below
default: not set
last_output ：v. 0.4.6 total reads 2868 total discontinuity blips 0,  total overflows 0

**Comment by rdp** [comment]
Does it record microphone ok? what os?

**Comment by dttlgotv** [comment]
Yes. It record microphone well.

My os is windows 7.

**Comment by rdp** [comment]
ffmpeg records it ok? could you send me the console output of a working
good ffmpeg run please?

**Comment by dttlgotv** [comment]
C:\Users\guoxinghua>ffmpeg -f dshow -i audio="virtual-audio-capturer" -acodec li
bopus gxh.opus
ffmpeg version 2.5.2 Copyright (c) 2000-2014 the FFmpeg developers
  built on Dec 30 2014 17:18:09 with gcc 4.9.2 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3
 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --ena
ble-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --e
nable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-lib
gsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencor
e-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enabl
e-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-l
ibtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-
libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-l
ibwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --ena
ble-lzma --enable-decklink --enable-zlib
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Guessed Channel Layout for  Input Stream #0.0 : stereo
Input #0, dshow, from 'audio=virtual-audio-capturer':
  Duration: N/A, start: 16258.072000, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
File 'gxh.opus' already exists. Overwrite ? [y/N] y
[libopus @ 00670940] No bit rate set. Defaulting to 96000 bps.
Output #0, opus, to 'gxh.opus':
  Metadata:
    encoder         : Lavf56.15.102
    Stream #0:0: Audio: opus (libopus), 48000 Hz, stereo, s16, 96 kb/s
    Metadata:
      encoder         : Lavc56.13.100 libopus
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> opus (libopus))
Press [q] to stop, [?] for help
size=     141kB time=00:00:14.69 bitrate=  78.8kbits/s

**Comment by dttlgotv** [comment]
expert:
        any response?

**Comment by rdp** [comment]
OK registry values after a run with ffmpeg and then run with your own?

**Comment by dttlgotv** [comment]
yes.

**Comment by rdp** [comment]
(what are they both times)
Also when you capture the microphone vs. the virtual audio, what is the HZ
for each (like 44100hz)?

**Comment by dttlgotv** [comment]
same hz, 48000

**Comment by rdp** [comment]
shoot I don't know then, sorry about that! If you figure it out let me
know. How does the audio sound again? patchy?

**Comment by dttlgotv** [comment]
Sometimes there is some noise in the recorded audio. I am sad that the ffmpeg command line can work well use same capture sample rate.

Any advice?

**Comment by dttlgotv** [comment]
It seems that 32000 and 48000 are well in my app. But 44100 is bad, the captured audio has noise.

**Comment by rdp** [comment]
full command line and uncut console output please?

**Comment by dttlgotv** [comment]
Sorry for late response.

I clarify the question again.  I use this dll to capture audio , and the result is below:

1. sound card out parameter,  sample rate 44100, channels 2, the audio got from av_read_frame  has noise. it is bad
2. sound card out parameter, sample rate 48000, channels 2, the audio got from av_read_frame has no noise, it is well.
3. sound card out parameter, sample rate 96000, channels 2, the audio got from av_read_frame has no noise, it is well.

These results are got by my app. I do not know what is different about 44100 with other. Do you know?

And in the other side, I use ffmepg command line to test, all are good.


Please give me some advice. Thanks a lot.

**Comment by rdp** [comment]
is your "sound system" 48000 ? (like normal playback?)

**Comment by dttlgotv** [comment]
sound system out sample rate can be set.
I use 44100,  av_read_frame get noise.
And I use 48000, av_read_frame get no noise.
It can be seen in one computer. But in the other computer, this issue can not be seen.


I want to know there is any trick about using this component using av_read_frame function.

Hope your answer.

**Comment by rdp** [comment]
OK does it only get "noise" if the two don't match?

**Comment by rdp** [comment]
Try with the latest, reopen if still getting this prob.
