### ISSUE TITLE
Fantastic! WinXP Code?

### ISSUE THREAD

**Issue by Noitidart** [rdp/virtual-audio-capture-grabber-device#17]
Hi there, this is really nice. I'm porting this to a firefox addon, but I noticed for winxp you recomend using sndvol, I was hoping to provide xp compatibility programtically, can you share that code please?

**Comment by rdp** [comment]
there is no equivalent in XP unfortunately, only built in "record what you
hear" options some sound cards/drivers provided, though other things like
VAC or vb.net work there probably.
GL!

**Comment by rdp** [comment]
no easy work around :\

**Comment by Noitidart** [comment]
Thanks rdp for leaving open this long.
