### ISSUE TITLE
audiosniffer.dll causing application crash

### ISSUE THREAD

**Issue by syam38** [rdp/virtual-audio-capture-grabber-device#20]
I am using ffmpeg to record audio on my windows 7 desktop.The audiosniffer.dll is used to grab the audio from the sound card,this is causing the ffmpeg.exe to crash. The application error log gives the _faulting module path_ as audiosniffer.dll's path and the  _faulting Application path_ as the path for  _ffmpeg.exe_.
ffmpeg works perfectly most of the times but I am facing this issue some times.

Screenshot of the error log
![erroredited](https://cloud.githubusercontent.com/assets/13881107/25081146/302651f4-2366-11e7-8600-41b4a9e2aef5.JPG)

I am not able to find the exact reason why audio_sniffer.dll is causing the application to crash.Is it something related to the exceptions thrown by the dll?.The exception code of the error quotes it as Access Violation.

**Comment by rdp** [comment]
now prompt as to why or assert or anything?

**Comment by syam38** [comment]
Hey,I got the exact reason which is causing the issue. I am using headset with a usb port  for recording the audio.When i unplug the headset while the recording is in progress, it is causing the _ffmpeg.exe_ to crash.As the exception code in error report says it as _Access Violation_, may be the dll is trying to access the source for the audio which is not available.

Is there any work around for that?

**Comment by rdp** [comment]
any exact message(s)?

**Comment by syam38** [comment]
This is the error log screenshot which i got.The exception code says it as Access Violation.

![erroredited](https://cloud.githubusercontent.com/assets/13881107/25272679/6d7a290c-26a6-11e7-8705-a4be527cec3d.JPG)

**Comment by rdp** [comment]
are you running ffmpeg from the command line? what about ffmpeg_g.exe
(there's one here):
https://sourceforge.net/projects/ffmpegwindowsbi/files/?source=navbar

**Comment by syam38** [comment]
Yes,through command line.Is ffmpeg_g.exe something different from ffmpeg.exe?

**Comment by rdp** [comment]
has debug symbols, who knows, maybe it'll matter, what I'm looking for is
an assert failure somehow...or a backtrace...

**Comment by wqter-git** [comment]
Manually build the source, register the dll, and you can debug into the code.
In my case, after unplugging the default audio device, and quit ffmpeg,
the exception will be thrown in loopBackRelease() around pAudioClient->Stop(); 
I guess the device pAudioClient pointing to becomes invalid.

**Comment by syam38** [comment]
I am glad that you too encountered the similar issue.Is there any work around to suppress the exceptions thrown?.

**Comment by wqter-git** [comment]
HI  I just found the lines of code that would throw exception, and commented out the clean-up code to avoid (since the process will exit then).
But this is not a reasonable solution, to handle this issue we need to detect the change of default audio device and reset the filter. per my understanding.
 
 ------------------ Original ------------------

**Comment by rdp** [comment]
at lines were commented out?

**Comment by rdp** [comment]
OK I was able to repro it and actually kind of fixed it in 4b95810 I wonder if it should "quit feeding" the output (like abort the graph) if this occurs (they unplug headphones)? Today it just pauses.  Yeah it probably should...hmm...

**Comment by rdp** [comment]
OK in f5aae2a made it "interrupt" the recording if it can no longer gather anything, this seemed OK in my head anyway.
