### ISSUE TITLE
Is there any way to use this without install `screen capture recorder` packet

### ISSUE THREAD

**Issue by zhaohuaxishi** [rdp/virtual-audio-capture-grabber-device#21]
I use ffmpeg(libavdevice, not the command line tool) with this to capture the "wave out sound" of my computer. everything works perfect excpet that i have to install `screen capture recorder` first and for me, the size of the packet is too big.

Is there any way that i can use the functionality without install the packet? i tried to packet audiosniffer.dll with my program, but it not working(my program crash).

**Comment by rdp** [comment]
You may need to install the MSVC 2010 runtime as well?

**Comment by rdp** [comment]
Yes it is possible, just register the .dll (and install the MSVC 2010 runtime) let me now if not working...
