### ISSUE TITLE
Fail to build audio_sniffer_2008.sln on Windows 8.1

### ISSUE THREAD

**Issue by PorkPiePie** [rdp/virtual-audio-capture-grabber-device#22]
I'm trying to follow the **how_to_setup_code.txt** guide use it on **Windows 8.1**

Unfortunally I could not install the **Windows SDK 7.1** on **Windows 8.1**, then I built the **baseclasses.sln** of the **Windows SDK 7.0 version**.

Then I'm getting some **error LINK: .... void ** even include the header and lib files from baseclasses Release and Debug.

**Comment by rdp** [comment]
I recently had luck installing the windows SDK 7.1 on windows 10, how does
yours fail?

**Comment by PorkPiePie** [comment]
I did this:
1 - I built the **baseclasses.sln** on Windows 10 in the **Release/Release_MBCS/Debug/Debug_MBCS**  **win32** mode to produce **strmbasd.lib** and  **strmbase.lib**.

2 - I went to **...\virtual-audio-capture-grabber-device\source_code\acam\audio_sniffer_2008** directory and I opened the **audio_sniffer_2008.sln**.  I setted all the **includes** and **library** deps to **C: ...\Microsoft SDKs\Windows\v7.1\Samples\multimedia\directshow\baseclasses**

And I went to build that in **win32,** as the result I 

1>LINK : fatal error LNK1181: cannot open input file 'strmbase.lib'

**Comment by rdp** [comment]
maybe there is another option that isn't the _2008 option? taht was for
MSVC 2008

**Comment by rdp** [comment]
2010

**Comment by PorkPiePie** [comment]
I built **virtual audio output sniffer.sln** and generated the **audio_sniffer.dll**. I ran **register_run_as_admin.bat** and it was ok. And I listed the dshow devices on ffmpeg, but I didn't found out any drive install.

`
[dshow @ 0000000001cc2920] DirectShow video devices (some may be both video and
audio devices)

[dshow @ 0000000001cc2920]  "WebCam SC-13HDL12131N"

[dshow @ 0000000001cc2920]     Alternative name "@device_pnp_\\?\usb#vid_2232&pi
d_1035&mi_00#7&2a89fef2&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global"

[dshow @ 0000000001cc2920] DirectShow audio devices

[dshow @ 0000000001cc2920]  "Microfone (Realtek High Definition Audio)"

[dshow @ 0000000001cc2920]     Alternative name "@device_cm_{33D9A762-90C8-11D0-
BD43-00A0C911CE86}\wave_{E1084966-BA1C-4164-8315-CB66FCBB5497}"
dummy: Immediate exit requested
` 

So is there something else step that I'm missing?

**Comment by rdp** [comment]
make sure the 32 vs. 64 bittedness of your ffmpeg matches the one you
registered...

**Comment by rdp** [comment]
If there is still a problem try with visual studio 2010 express and report back, cheers!
