### ISSUE TITLE
Record auido failed.

### ISSUE THREAD

**Issue by zhlxys** [rdp/virtual-audio-capture-grabber-device#29]
ffmpeg -f dshow -i video="screen-capture-recorder" -f dshow -i audio="virtual-audio-capturer" -vcodec libx264 -acodec libmp3lame -s 1280*720 -r 25 -f segment -segment_time 30 -reset_timestamps 1 screen_20190417160135.716000_%d.mp4

![image](https://user-images.githubusercontent.com/12048003/56275619-a3bfe780-6133-11e9-9455-51078735ea97.png)

**Comment by rdp** [comment]
Is your speaker or headphones plugged in?

**Comment by zhlxys** [comment]
issue solved after speaker plugged in.
