### ISSUE TITLE
acm project build error windows 10

### ISSUE THREAD

**Issue by herbzone127** [rdp/virtual-audio-capture-grabber-device#34]
I followed all directions from readme file but i couldn't get success to run in windows 10, there is an error for streams.h file

**Comment by rdp** [comment]
acm?

**Comment by herbzone127** [comment]
@rdp  sorry, I'm talking about this project  acam.vcxproj

**Comment by rdp** [comment]
Do you have streams.h anywhere?

**Comment by herbzone127** [comment]
> Do you have streams.h anywhere?

no i dont have, I saw it will come with Windows 7 SDK

**Comment by rdp** [comment]
Did you install the SDK? Thanks!

**Comment by herbzone127** [comment]
no, i dont want to inatall window 7 sdk, is there any way to use this library without window 7 sdk ,  or include streams.h file in project to run it

**Comment by rdp** [comment]
I'm not aware of one, sorry!   It's not too bad of a download...and kind of
necessary if you want to build from source.  You could use the
distributable binaries without it, cheers!

**Comment by herbzone127** [comment]
if that possible can you provide me dll for streams.h, it would be a great help to me. and my requirement is to run this project on windows 10 sdk without windows 7 sdk

**Comment by rdp** [comment]
Here is the .dll
https://github.com/rdp/virtual-audio-capture-grabber-device/tree/master/source_code/Release
I think you need to install the visual studio runtime as well or something
https://github.com/rdp/screen-capture-recorder-to-video-windows-free/blob/c61aea9b23d07a69bfb2b2d568ee172db1394cc5/innosetup_installer_options.iss
Good luck!

**Comment by herbzone127** [comment]
no, im talking about stream.h dll actually i need source code for audio sniffer

**Comment by rdp** [comment]
Yeah that's part of the SDK I guess...
