### ISSUE TITLE
graphedit report error

### ISSUE THREAD

**Issue by ghost** [rdp/virtual-audio-capture-grabber-device#4]
My OS is win7.

I have installed virtual-audio-capture-grabber-device.

I execute ffmpeg -f dshow -i audio="virtual-audio-capturer" record.wav is ok.

I use microphone in graphedit is ok.

I use virtual-audio-capturer in graphedit report "the graph could not change state."
virtual-audio-capturer --> wav dest --> file writer.

**Comment by rdp** [comment]
It worked for me just now using "WAV Dest" mentioned here: https://www.codeproject.com/Articles/31788/Audio-Capture-with-DirectShow-Part "any alternative" sorry for the delay please reopen if problem stll reproducible, thanks!
