### ISSUE TITLE
if no audio devices causes a segfault

### ISSUE THREAD

**Issue by rdp** [rdp/virtual-audio-capture-grabber-device#8]
which is never good... :P

**Comment by nhjm449** [comment]
Yep, I see a segfault after "IMMDeviceEnumerator::GetDefaultAudioEndpoint failed: hr = 0x80070490" (ERROR_NOT_FOUND).

It's possible that pMMDevice is undefined when pMMDevice->Activate() is called:

https://github.com/rdp/virtual-audio-capture-grabber-device/blob/8b3a686480f4088bbc74d7bd090db215565d4253/source_code/acam/loopback-capture.cpp#L67

(Using Screen Capture Recorder v0.12.8)

**Comment by rdp** [comment]
hopefully fixed in 54aa9ee thank you for the report.
